development:
  adapter: mongomapper
  host: 127.0.0.1
  database: adam_test_development
  port: 27017

test: &TEST
  adapter: mongomapper
  host: localhost
  database: adam_test_test_123
  port: 27017

production:
  adapter: mongomapper
  host: localhost
  database: adam_test_production
  port: 27017

cucumber:
  <<: *TEST
